root = "."
tmp_dir = "tmp"

[build]
  cmd = "true"
  full_bin = "nginx -p . -c nginx-dev.conf"
  include_ext = ["html", "css", "js", "svg", "xml", "json", "conf"]
  include_dir = ["public"]
  exclude_dir = ["tmp"]
  delay = 100
  stop_on_error = false
  send_interrupt = true
  kill_delay = "500ms"

[proxy]
  enabled = true
  proxy_port = 8080
  app_port = 8081

[misc]
  clean_on_exit = true
