server_tokens off;

gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml application/rss+xml application/atom+xml;

index index.html;
absolute_redirect off;

# canonical url
rewrite ^/(.*?)/+$ /$1 permanent;

location / {
    add_header Cache-Control "public, max-age=0, s-maxage=600, stale-while-revalidate=86400, stale-if-error=604800";

    # we don't use ... @markdown =404, a named location like @markdown needs to be at the end
    try_files $uri $uri.html $uri/index.html @markdown;
}

location @markdown {
    default_type text/html;
    js_content markdown.mark;
}
