load_module modules/ngx_http_js_module.so;
worker_processes auto;
# non root so need this
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    client_body_temp_path /tmp/nginx_body;
    proxy_temp_path       /tmp/nginx_proxy;
    fastcgi_temp_path     /tmp/nginx_fastcgi;
    uwsgi_temp_path       /tmp/nginx_uwsgi;
    scgi_temp_path        /tmp/nginx_scgi;

    js_engine qjs;
    js_import main from webring.js;
    js_import comments from comments.js;

    server {
        listen 8080;
        listen [::]:8080;
        server_name mrrrp.cat;
        root /var/www/html;

        location = /wrnext { js_content main.wrnext; }
        location = /wrprev { js_content main.wrprev; }
        location = /comments {
            client_body_in_single_buffer on;
            js_content comments.get_comments;
        }

        include http.conf;
    }

    server {
        listen 8080;
        listen [::]:8080;
        server_name www.mrrrp.cat;

        return 301 https://mrrrp.cat$request_uri;
    }
}
