#!/bin/sh
set -e

size="${SIZE:-128}"
resize="${size}x${size}^"
[ -n "$FIT" ] && resize="${size}x${size}"

in="$1"
out="${2:-${in%.*}.png}"

magick "$in" -background none \
	-resize "$resize" \
	-gravity center -extent "${size}x${size}" \
	-strip \
	"$out"
