worker_processes auto;

pid /tmp/nginx.pid;
error_log /dev/stdout error;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;

    client_body_temp_path /tmp/nginx_body;
    proxy_temp_path       /tmp/nginx_proxy;
    fastcgi_temp_path     /tmp/nginx_fastcgi;
    uwsgi_temp_path       /tmp/nginx_uwsgi;
    scgi_temp_path        /tmp/nginx_scgi;

    # https://nginx.org/en/docs/njs/install.html
    # https://nginx.org/en/linux_packages.html
    #
    # official packages debian: nginx, nginx-module-njs
    # debian:                   nginx, libnginx-mod-http-js
    # arch:                     nginx, nginx-mod-njs

    js_import main from ngx_webring.js;
    js_import comments from ngx_comments.js;
    js_import markdown from ngx_markdown.js;
    js_engine qjs;

    server {
        listen 8080;
        listen [::]:8080;
        server_name mrrrp.cat;

        # "-p" sets the "path prefix" which all config resolves under.
        # then, we set the html "root" which is under ./public where the content
        # resolves from
        root ..;

        location = /wrnext { js_content main.wrnext; }
        location = /wrprev { js_content main.wrprev; }
        location = /comments {
            client_body_in_single_buffer on;
            js_content comments.comments;
        }

        server_tokens off;
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml application/rss+xml application/atom+xml;

        index index.html;
        absolute_redirect off;

        # canonical url
        rewrite ^/(.*?)/+$ /$1 permanent;

        location / {
            add_header Cache-Control "public, max-age=0, s-maxage=600, stale-while-revalidate=86400, stale-if-error=604800";

            # we don't use ... @markdown =404, a named location like @markdown needs to be at the end
            try_files $uri $uri.html $uri/index.html @markdown;
        }

        location @markdown {
            default_type text/html;
            js_content markdown.mark;
        }

    }

    server {
        listen 8080;
        listen [::]:8080;
        server_name www.mrrrp.cat;

        return 301 https://mrrrp.cat$request_uri;
    }
}
