name: prod
on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency: prod

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  prod:
    runs-on: mrrrp-set
    environment:
      name: production
      url: https://mrrrp.cat
    env:
      IMAGE: ghcr.io/l1mey112/mrrrp
    steps:
      - uses: actions/checkout@v4

      # my runners are daemonless
      - name: build & push image
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq podman
          echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
          sudo podman build --isolation=chroot -t "$IMAGE:${{ github.sha }}" -t "$IMAGE:latest" .
          sudo podman push "$IMAGE:${{ github.sha }}"
          sudo podman push "$IMAGE:latest"

      - uses: azure/setup-kubectl@v4

      - name: apply
        run: |
          sed -i "s|newTag: .*|newTag: ${{ github.sha }}|" .github/kustomization.yaml
          kubectl apply -k .github
          kubectl -n mrrrp-website rollout status deploy/deployment --timeout=300s
